name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  JAVA_VERSION: "17" # Changed to match your build.gradle.kts
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: |
          gradle wrapper
          chmod +x ./gradlew

      - name: Compile
        run: ./gradlew build

      - name: Run linter
        run: ./gradlew checkstyleMain

      - name: Run unit tests
        run: ./gradlew test --rerun-tasks

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            **/build/reports/tests/
            **/build/test-results/

  code-quality:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          gradle wrapper
          chmod +x ./gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        continue-on-error: true

      - name: Run SpotBugs
        run: ./gradlew spotbugsMain spotbugsTest
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        continue-on-error: true

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        continue-on-error: true

      - name: Run SonarQube analysis
        run: ./gradlew sonar
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Upload Checkstyle results
        uses: actions/upload-artifact@v4
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        if: always()
        with:
          name: checkstyle-results
          path: |
            **/build/reports/checkstyle/

      - name: Upload SpotBugs results
        uses: actions/upload-artifact@v4
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        if: always()
        with:
          name: spotbugs-results
          path: |
            **/build/reports/spotbugs/

      - name: Upload PMD results
        uses: actions/upload-artifact@v4
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        if: always()
        with:
          name: pmd-results
          path: |
            **/build/reports/pmd/

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: |
          gradle wrapper
          chmod +x ./gradlew

      - name: Run OWASP Dependency Check
        run: ./gradlew dependencyCheckAnalyze
        continue-on-error: true
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Upload OWASP results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: |
            **/build/reports/dependency-check-report.html

  package:
    runs-on: ubuntu-latest
    needs: [code-quality, security-scan]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: gradle

      - name: Make gradlew executable
        run: |
          gradle wrapper
          chmod +x ./gradlew

      - name: Build application
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: ./gradlew bootJar -x test

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar
          path: |
            **/build/libs/*.jar
