name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 0.1.7)'
        required: true
        type: string

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: wrapper
          
    - name: Validate project
      run: ./gradlew build -x test
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      
    - name: Run full test suite
      run: ./gradlew test
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      
    - name: Verify package can be built
      run: ./gradlew assemble
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: wrapper
          
    - name: Extract version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          VERSION="${{ github.event.inputs.version }}"
        else
          VERSION=${GITHUB_REF#refs/tags/v}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
        
    - name: Update version in build.gradle.kts
      run: |
        sed -i "s/version = \".*\"/version = \"${{ steps.version.outputs.version }}\"/" build.gradle.kts
        
    - name: Build release artifacts
      run: |
        ./gradlew clean build publishToMavenLocal -x test
        
    - name: Create release notes
      id: release_notes
      run: |
        echo "## What's Changed" > release_notes.md
        echo "" >> release_notes.md
        
        # Get commits since last tag
        LAST_TAG=$(git describe --tags --abbrev=0 HEAD~1 2>/dev/null || echo "")
        if [ -n "$LAST_TAG" ]; then
          echo "### Commits since $LAST_TAG:" >> release_notes.md
          git log $LAST_TAG..HEAD --oneline --pretty=format:"- %s (%h)" >> release_notes.md
        else
          echo "### All commits in this release:" >> release_notes.md
          git log --oneline --pretty=format:"- %s (%h)" >> release_notes.md
        fi
        
        echo "" >> release_notes.md
        echo "## Artifacts" >> release_notes.md
        echo "- **JAR**: \`gradldromus-${{ steps.version.outputs.version }}.jar\`" >> release_notes.md
        echo "- **Sources**: \`gradldromus-${{ steps.version.outputs.version }}-sources.jar\`" >> release_notes.md
        echo "- **Javadoc**: \`gradldromus-${{ steps.version.outputs.version }}-javadoc.jar\`" >> release_notes.md
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: Release v${{ steps.version.outputs.version }}
        body_path: release_notes.md
        files: |
          build/libs/gradldromus-${{ steps.version.outputs.version }}.jar
          build/libs/gradldromus-${{ steps.version.outputs.version }}-sources.jar
          build/libs/gradldromus-${{ steps.version.outputs.version }}-javadoc.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-maven-central:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    needs: [ validate, release ]
    if: github.repository == 'clojang/gradldromus'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Update version in build.gradle.kts
        run: |
          sed -i "s/version = \".*\"/version = \"${{ needs.release.outputs.version }}\"/" build.gradle.kts

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import --quiet
          
          # List keys to verify import
          echo "Imported GPG keys:"
          gpg --list-secret-keys --keyid-format LONG
          
          # Export the key to verify it's available
          GPG_KEY_ID="${{ secrets.GPG_KEY_ID }}"
          echo "Verifying key $GPG_KEY_ID is available..."
          gpg --list-secret-keys $GPG_KEY_ID

      - name: Publish to Maven Central
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          SONATYPE_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          SIGNING_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

  publish-github-packages:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: [ validate, release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Update version in build.gradle.kts
        run: |
          sed -i "s/version = \".*\"/version = \"${{ needs.release.outputs.version }}\"/" build.gradle.kts

      - name: Publish to GitHub Packages
        run: |
          ./gradlew publishPluginMavenPublicationToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-documentation:
    name: Update Documentation
    runs-on: ubuntu-latest
    needs: [ release ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Update version in README
        run: |
          sed -i 's/<version>[0-9]*\.[0-9]*\.[0-9]*<\/version>/<version>${{ needs.release.outputs.version }}<\/version>/g' README.md
          sed -i "s/gradldromus:[0-9]*\.[0-9]*\.[0-9]*/gradldromus:${{ needs.release.outputs.version }}/g" README.md

      - name: Update version in build.gradle.kts
        run: |
          sed -i "s/version = \".*\"/version = \"${{ needs.release.outputs.version }}\"/" build.gradle.kts

      - name: Generate Javadoc
        run: |
          ./gradlew javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/javadoc
          destination_dir: javadoc

      - name: Commit version updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md build.gradle.kts
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update documentation for release v${{ needs.release.outputs.version }}"
            git push origin main
          fi